parameters:
  - name: job
    type: string
  - name: jobResources
    type: string
  - name: serviceConnection
    type: string
  - name: infraPath
    type: string
  - name: parametersPath
    type: string
  - name: rgName
    type: string
  - name: location
    type: string
  - name: overrideParameters
    type: string


jobs:
  - job: "${{ parameters.job }}"
    displayName: "Job: Provision Infrstructure - ${{ parameters.jobResources }}"
    steps:

      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: "Resource Group"
          AzureResourceManagerConnection: "${{parameters.serviceConnection}}"
          action: "Create Or Update Resource Group"
          resourceGroupName: "${{ parameters.rgName }}"
          location: "${{ parameters.location }}"
          templateLocation: "Linked artifact"
          csmParametersFile: "${{ parameters.parametersPath }}/main.bicepparam"
          csmFile: "${{ parameters.infraPath }}/main.bicep"
          deploymentMode: "Incremental"
          overrideParameters: "${{parameters.overrideParameters}}"
