parameters:
  - name: job
    type: string
  - name: jobResources
    type: string
  - name: serviceConnection
    type: string
  - name: infraPath
    type: string
  - name: rgName
    type: string
  - name: location
    type: string
  - name: overrideParameters
    type: string

jobs:
  - job: "${{ parameters.job }}"
    displayName: "Job: Provision Infrstructure - ${{ parameters.jobResources }}"
    steps:
      - task: AzurePowerShell@5
        inputs:
          azureSubscription: "${{ parameters.serviceConnection }}"
          ScriptType: "FilePath"
          ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/compile-bicep-to-arm.ps1"
          ScriptArguments: "
            -filePath $(System.DefaultWorkingDirectory)/${{ parameters.infraPath }} `
            -bicepTemplate main.bicep `
            -outFile main.json"
          azurePowerShellVersion: "LatestVersion"