parameters:
  - name: job
    type: string
  - name: resource
    type: string
  - name: serviceConnection
    type: string
  - name: infraPath
    type: string
  - name: rgName
    type: string
  - name: location
    type: string
  - name: overrideParameters
    type: string
  - name: dependsOn
    type: object
    default: []


jobs:


    - job: "${{ parameters.job }}"
      displayName: "Job: Provision Infrstructure - ${{ parameters.resource }}"
      dependsOn:
          - ${{ each dep in parameters.dependsOn }} :
            - ${{ dep }}
      condition: "succeeded()"
      steps:
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: "${{ parameters.serviceConnection }}"
            ScriptType: "FilePath"
            ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/compile-bicep-to-arm.ps1"
            ScriptArguments: "
              -filePath $(System.DefaultWorkingDirectory)/${{ resource.path }}/${{ parameters.infraPath }} `
              -bicepTemplate main.bicep `
              -outFile main.json"
            azurePowerShellVersion: "LatestVersion"
            
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: "Resource Group"
            AzureResourceManagerConnection: "${{parameters.serviceConnection}}"
            action: "Create Or Update Resource Group"
            resourceGroupName: "${{ parameters.rgName }}"
            location: "${{ parameters.location }}"
            templateLocation: "Linked artifact"
            csmFile: "${{ parameters.infraPath }}/${{ resource.path }}/main.json"
            deploymentMode: "Incremental"
            overrideParameters: "${{parameters.overrideParameters}}"
