parameters:
  - name: stage
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: condition
    type: string
    default: succeeded()
  - name: serviceConnection
    type: string
  - name: rgName
    type: string
  - name: infraPath
    type: string
  - name: location
    type: string
  - name: owner
    type: string
  - name: costCenter
    type: string
  - name: application
    type: string
  - name: desc
    type: string
  - name: repo
    type: string
  - name: version
    type: string
  - name: partName
    type: string
  - name: resource
    type: string
  - name: resources
    type: object
    default: []

stages:
  - stage: "${{ parameters.stage }}"
    displayName: "Stage: Provision Infrastructure - ${{ parameters.resource }}"
    dependsOn: "${{ parameters.dependsOn }}"
    condition: "${{ parameters.condition }}"
    jobs:

      - ${{ each resource in parameters.resources }} :

      - template: "../jobs/job-deploy-infra.yml@self"
        parameters:
          job: "JobDeployInfra${{ resource.id }}"
          resource: "${{ resource.name }}"
          dependsOn: ${{ resource.dependencies }}
          serviceConnection: "${{ parameters.serviceConnection }}"
          infraPath: "${{ parameters.infraPath }}/${{resource.path}}"
          rgName: ${{ parameters.rgName }}
          location: ${{ parameters.location }}
          overrideParameters: >-
            -owner "${{ parameters.owner }}"
            -costCenter "${{ parameters.costCenter }}"
            -application "${{ parameters.application }}"
            -descp "${{ parameters.desc }}"
            -repo "${{ parameters.repo }}"
            -version "${{ parameters.version }}"
            -partName "${{ parameters.partName }}"
            -location "${{ parameters.location }}"
            
