parameters:
  - name: stage
    type: string
    default: succeeded()
  - name: resource
    type: string
  - name: serviceConnection
    type: string
  - name: rgName
    type: string
  - name: location
    type: string
  - name: owner
    type: string
  - name: costCenter
    type: string
  - name: application
    type: string
  - name: desc
    type: string
  - name: repo
    type: string

stages:
  - stage: "${{ parameters.stage }}"
    displayName: "Stage: Provision Infrastructure - ${{ parameters.resource }}"
    jobs:
      - template: "../jobs/job-deploy-rg.yml@self"
        parameters:
          job: "JobDeployRg"
          jobResources: "${{ parameters.resource }}"
          serviceConnection: "${{ parameters.serviceConnection }}"
          rgName: ${{ parameters.rgName }}
          location: ${{ parameters.location }}
          owner: "${{ parameters.owner }}"
          costCenter : "${{ parameters.costCenter }}"
          application : "${{ parameters.application }}"
          desc : "${{ parameters.desc }}"
          repo:  "${{ parameters.repo }}"

