trigger: none

pool:
  vmImage: "windows-latest"

stages:
  - stage: StageProvisionRg
    displayName: "Stage : Provision rg"
    jobs:
      - job: jobProvisionRg
        displayName: "Job - Provision rg"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: "Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)"
              ScriptType: "FilePath"
              ScriptPath: "$(System.DefaultWorkingDirectory)/scripts/create-resource-group.ps1"
              ScriptArguments: '-location westeurope `
                -rgName "rg-fromdevops-01" `
                -owner "Nobody" `
                -costCenter "135453" `
                -application "TestFromDevops" `
                -description "some test made with devops and powershell" `
                -repo "https://dev.azure.com/MouhsineAyi/CICD_Project_Accademicts"'
              azurePowerShellVersion: "LatestVersion"
