trigger: none

parameters:
  - name: variableGroup
    type: string
    default: vg-pfu-infrastructure
  - name: serviceConnection
    type: string
    default: Visual Studio Professional Subscription(0f7a3b62-c1a4-4aa9-97c3-3bf5f497b5ab)
  - name: environment
    type: string
    values:
      - dev
      - acc
      - prod

variables:
  - group: ${{ parameters.variableGroup }}
  - name: version
    value: 001
  - name: rgName
    value: "rg-$(companyShort)-$(domainShort)-$(appShort)-$(locationAbbr)-${{ parameters.environment }}-$(version)"
  - name: partName
    value: "$(companyShort)-$(domainShort)-$(appShort)-$(locationAbbr)-${{ parameters.environment }}-$(version)"

stages:
  - template: "./templates/stages/stage-deploy-rg.yml@self"
    parameters:
      stage: StageProvisionRG
      resource: "RG"
      serviceConnection: "${{ parameters.serviceConnection }}"
      rgName: "$(rgName)"
      location: "$(location)"
      owner: "$(owner)"
      costCenter: "$(costCenter)"
      application: "$(application)"
      desc: "$(desc)"
      repo: "$(repo)"

  - template: "./templates/stages/stage-deploy-infra.yml@self"
    parameters:
      stage: StageProvisionInfrastructure_storages
      dependsOn:
        - StageProvisionRG
      condition: "succeeded()"
      serviceConnection: "${{ parameters.serviceConnection }}"
      rgName: "$(rgName)"
      infraPath: "infrastructure"
      location: "$(location)"
      owner: "$(owner)"
      costCenter: "$(costCenter)"
      application: "$(application)"
      desc: "$(desc)"
      repo: "$(repo)"
      version: "$(version)"
      partName: "$(partName)"
      resourceBase: "storage"
      resources:
        - manId: "UserManagedIdentity"
          id: "UserManagedIdentity"
          name: "User Managed Identity"
          job: "JobDeployInfrastructureManagedId"
          path: "managedId"
          dependencies: []
          paramOverride: >-

        - kv: "keyVault"
          id: "keyVault"
          name: "Key Vault"
          job: "JobDeployInfrastructureKeyVault"
          path: "keyVault"
          dependencies: [JobDeployInfraUserManagedIdentity]
          paramOverride: >-




  - template: "./templates/stages/stage-deploy-infra.yml@self"
    parameters:
      stage: StageProvisionInfrastructure_web
      dependsOn:
        - StageProvisionInfrastructure_storages
      condition: "succeeded()"
      serviceConnection: "${{ parameters.serviceConnection }}"
      rgName: "$(rgName)"
      infraPath: "infrastructure"
      location: "$(location)"
      owner: "$(owner)"
      costCenter: "$(costCenter)"
      application: "$(application)"
      desc: "$(desc)"
      repo: "$(repo)"
      version: "$(version)"
      partName: "$(partName)"
      resourceBase: "web"
      resources:
          - webApp: "webApp"
            id: "webApp"
            name: "Web Api"
            job: "JobDeployInfrastructureWebApp"
            path: "webApp"
            dependencies: []
            paramOverride: >-
              -branch "main"
              -repoUrl "https://github.com/Mouhsine-inetum/Food-delivery-server-alternate.git"
              -skuApiServiceName "B1"
              -skuApiServiceCapacity 3

  # - template: "./templates/stages/stage-deploy-infra.yml@self"
  #   parameters:
  #     stage: StageProvisionInfrastructureDataFactory
  #     dependsOn:
  #       - StageProvisionInfrastructureLogAnalytics
  #     condition: succeeded()
  #     resource: "Data Factory"
  #     serviceConnection: "${{ parameters.serviceConnection }}"
  #     rgName: "$(rgName)"
  #     infraPath: "infra/data-factory"
  #     location: "$(location)"
  #     owner: "$(owner)"
  #     costCenter: "$(costCenter)"
  #     application: "$(application)"
  #     desc: "$(desc)"
  #     repo: "$(repo)"
  #     appShort: "$(appShort)"
  #     domainShort: "$(domainShort)"
  #     version: "$(version)"
  #     env: "${{ parameters.environment }}"
